apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-docker-repo/backend:latest
          ports:
            - containerPort: 8001
          env:
            - name: ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URL
            - name: REDIS_HOST
              value: "redis://redis:6379"
            # AI/ML Configuration
            - name: AI_MATCHING_ENABLED
              value: "true"
            - name: EMBEDDING_MODEL
              value: "sentence-transformers/all-MiniLM-L6-v2"
            - name: SKILLS_VERIFICATION_ENABLED
              value: "true"
            - name: REPUTATION_V2_ENABLED
              value: "true"
            - name: MATCHING_CACHE_TTL
              value: "3600"
            # OAuth Configuration
            - name: OAUTH_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: OAUTH_ENCRYPTION_KEY
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SLACK_CLIENT_ID
            - name: SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SLACK_CLIENT_SECRET
            - name: JIRA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JIRA_CLIENT_ID
            - name: JIRA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JIRA_CLIENT_SECRET
            - name: TRELLO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: TRELLO_CLIENT_ID
            - name: TRELLO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: TRELLO_CLIENT_SECRET
            - name: ETH_NODE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: ETH_NODE_URL
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: STRIPE_SECRET
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: STRIPE_WEBHOOK_SECRET
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SENDGRID_API_KEY
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 5
---
# RQ Worker Deployment for Background Jobs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rq-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rq-worker
  template:
    metadata:
      labels:
        app: rq-worker
    spec:
      containers:
        - name: rq-worker
          image: your-docker-repo/backend:latest
          command: ["python", "-m", "rq", "worker", "--url", "redis://redis:6379"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URL
            - name: REDIS_HOST
              value: "redis://redis:6379"
            - name: AI_MATCHING_ENABLED
              value: "true"
            - name: EMBEDDING_MODEL
              value: "sentence-transformers/all-MiniLM-L6-v2"
            - name: SKILLS_VERIFICATION_ENABLED
              value: "true"
            - name: REPUTATION_V2_ENABLED
              value: "true"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
# RQ Dashboard Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rq-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rq-dashboard
  template:
    metadata:
      labels:
        app: rq-dashboard
    spec:
      containers:
        - name: rq-dashboard
          image: your-docker-repo/backend:latest
          command: ["rq-dashboard", "--redis-url", "redis://redis:6379", "--port", "9181", "--bind", "0.0.0.0"]
          ports:
            - containerPort: 9181
          env:
            - name: REDIS_HOST
              value: "redis://redis:6379"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: rq-dashboard
spec:
  selector:
    app: rq-dashboard
  ports:
    - protocol: TCP
      port: 9181
      targetPort: 9181 