apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-docker-repo/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URL
            - name: REDIS_HOST
              value: "redis://redis:6379"
            - name: ETH_NODE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: ETH_NODE_URL
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: STRIPE_SECRET
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: STRIPE_WEBHOOK_SECRET
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SENDGRID_API_KEY
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 