// Export all custom hooks from a single entry point
export { useApi, useApiMutation, useProjects, useProject, useUserProfile, useNotifications, useCreateProject, useUpdateProject, useDeleteProject } from './useApi'
export { useDebounce } from './useDebounce'
export { useLocalStorage } from './useLocalStorage'
export { useMediaQuery, useIsMobile, useIsTablet, useIsDesktop, useIsDarkMode } from './useMediaQuery'
export { useWebSocket, useNotificationWebSocket, useChatWebSocket } from './useWebSocket'
export { useClipboard } from './useClipboard'
export { useInterval } from './useInterval'
export { useOnClickOutside } from './useOnClickOutside'
export { useKeyPress, useKeyboardShortcut } from './useKeyPress'
export { useIntersectionObserver, useLazyLoad } from './useIntersectionObserver'
export { useForm } from './useForm'
export { usePagination } from './usePagination'
export { useLocation } from './useLocation'
export { useProjects as useProjectsOld } from './useProjects'
