name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          contracts/package-lock.json
          frontend/package-lock.json

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        pip install -r requirements.txt

    - name: Install Contract Dependencies
      working-directory: ./contracts
      run: npm install

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Lint Backend
      working-directory: ./backend
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run Contract Tests
      working-directory: ./contracts
      run: npx hardhat test

    - name: Run Backend Tests
      working-directory: ./backend
      run: |
        # Placeholder for pytest
        echo "Pytest not implemented yet"

    - name: Run Frontend Tests and Lint
      working-directory: ./frontend
      run: |
        npm run lint
        # Placeholder for Jest tests
        echo "Frontend tests not implemented yet"

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build 